name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Key Format
      run: |
        echo "Testing SSH key setup..."
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        echo "Checking key file..."
        ls -la ~/.ssh/
        
        echo "Testing key format..."
        ssh-keygen -y -f ~/.ssh/id_ed25519 || echo "Key format error"
        
    - name: Test SSH Connection
      continue-on-error: true
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        ssh -vvv -o ConnectTimeout=10 ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "echo 'Connection successful'"